// ABOUTME: Runs every code sample the course publishes through the interpreter, so a lesson
// ABOUTME: can never again show a learner source that the interpreter would reject.

use natural_core::{Library, NaturalError, run_in_library};
use std::path::PathBuf;

/// One published sample, as extracted from web/lessons.js.
struct Sample {
    where_: String,
    kind: String,
    source: String,
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/lesson-code.json")
}

/// Reads the extracted samples.
///
/// The fixture is regenerated by `scripts/extract-lesson-code.mjs`, which the verification
/// gate runs before the tests. A missing or stale fixture fails loudly rather than quietly
/// passing, because a silent skip here would recreate the gap this file exists to close.
fn load() -> (Vec<Sample>, Library) {
    let path = fixture_path();
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "could not read {}: {error}.\nRun: node scripts/extract-lesson-code.mjs",
            path.display()
        )
    });

    let samples = json_array(&raw, "samples")
        .into_iter()
        .map(|object| Sample {
            where_: json_string(&object, "where"),
            kind: json_string(&object, "kind"),
            source: json_string(&object, "source"),
        })
        .collect::<Vec<_>>();
    assert!(!samples.is_empty(), "the fixture holds no samples");

    let mut library = Library::new();
    for object in json_array(&raw, "library") {
        library.add(
            &json_string(&object, "name"),
            &json_string(&object, "source"),
        );
    }
    (samples, library)
}

#[test]
fn every_published_demo_runs_without_error() {
    let (samples, library) = load();
    let mut failures = Vec::new();

    for sample in samples.iter().filter(|s| s.kind == "demo") {
        // An INPUT-driven demo asks for values the fixture cannot know, so supplying a few
        // harmless ones keeps the run going far enough to prove the source compiles.
        match run_in_library(&sample.source, &library, &["1", "1", "1", "1"]) {
            Ok(_) => {}
            // Running out of supplied answers is not a defect in the sample.
            Err(NaturalError::InputRequired { .. }) => {}
            Err(error) => failures.push(format!("  {}\n    {error}", sample.where_)),
        }
    }

    assert!(
        failures.is_empty(),
        "{} published sample(s) do not run:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn every_demo_that_teaches_by_failing_actually_fails() {
    // Three lessons show a program going wrong on purpose. If one of them started working,
    // the lesson around it would be teaching a lie, which is as bad as a broken sample.
    let (samples, library) = load();
    let mut failures = Vec::new();

    for sample in samples.iter().filter(|s| s.kind == "demo-error") {
        if run_in_library(&sample.source, &library, &["1", "1", "1", "1"]).is_ok() {
            failures.push(format!("  {}", sample.where_));
        }
    }

    assert!(
        failures.is_empty(),
        "{} sample(s) are presented as failing but now succeed:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn every_exercise_starter_is_at_least_well_formed() {
    // A starter is deliberately incomplete, so it is allowed to fail for missing an END or
    // for asking a question the fixture cannot answer. What it must never do is fail with a
    // diagnostic about syntax the learner has not been taught to fix.
    let (samples, library) = load();
    let mut failures = Vec::new();

    for sample in samples.iter().filter(|s| s.kind == "starter") {
        match run_in_library(&sample.source, &library, &["1", "1", "1", "1"]) {
            Ok(_) => {}
            Err(
                NaturalError::MissingEnd
                | NaturalError::InputRequired { .. }
                | NaturalError::MissingEndDefine,
            ) => {}
            Err(error) => failures.push(format!("  {}\n    {error}", sample.where_)),
        }
    }

    assert!(
        failures.is_empty(),
        "{} exercise starter(s) fail for the wrong reason:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn every_library_object_compiles() {
    let (_, library) = load();
    let mut failures = Vec::new();
    for name in library.names() {
        let source = library.get(&name).expect("just listed");
        if let Err(error) = natural_core::parse_program(source) {
            failures.push(format!("  {name}\n    {error}"));
        }
    }
    assert!(
        failures.is_empty(),
        "{} library object(s) do not compile:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

// ---- a very small JSON reader ----
//
// The fixture is generated by our own script, so it needs reading rather than parsing in
// general. Taking a serde dependency into the test build to read two known keys would cost
// more than it saves.

fn json_array(raw: &str, key: &str) -> Vec<String> {
    let Some(start) = raw.find(&format!("\"{key}\": [")) else {
        return Vec::new();
    };
    let body = &raw[start..];
    let mut depth = 0usize;
    let mut objects = Vec::new();
    let mut current = String::new();
    let mut in_string = false;
    let mut escaped = false;

    for c in body.chars() {
        if in_string {
            current.push(c);
            if escaped {
                escaped = false;
            } else if c == '\\' {
                escaped = true;
            } else if c == '"' {
                in_string = false;
            }
            continue;
        }
        match c {
            '"' => {
                in_string = true;
                if depth > 0 {
                    current.push(c);
                }
            }
            '{' => {
                depth += 1;
                if depth > 0 {
                    current.push(c);
                }
            }
            '}' => {
                current.push(c);
                depth -= 1;
                if depth == 0 {
                    objects.push(std::mem::take(&mut current));
                }
            }
            ']' if depth == 0 => break,
            _ if depth > 0 => current.push(c),
            _ => {}
        }
    }
    objects
}

fn json_string(object: &str, key: &str) -> String {
    let needle = format!("\"{key}\": \"");
    let start = object
        .find(&needle)
        .unwrap_or_else(|| panic!("key {key} missing from {object}"))
        + needle.len();
    let mut out = String::new();
    let mut chars = object[start..].chars();
    while let Some(c) = chars.next() {
        match c {
            '"' => break,
            '\\' => match chars.next() {
                Some('n') => out.push('\n'),
                Some('t') => out.push('\t'),
                Some('r') => out.push('\r'),
                Some('u') => {
                    let hex: String = chars.by_ref().take(4).collect();
                    if let Some(c) = u32::from_str_radix(&hex, 16).ok().and_then(char::from_u32) {
                        out.push(c);
                    }
                }
                Some(other) => out.push(other),
                None => break,
            },
            other => out.push(other),
        }
    }
    out
}
